### PR TITLE
Add a module for the special case where the graph is a tree

### PR DESCRIPTION
**Pull request by ablondin**
This is a retry of pull request #6 (I chose the wrong base branch).

In the case where the graph G is a tree, it is possible to compute the leaf function in polynomial time, using a dynamic programming approach.

This pull request adds a module that implements this strategy.

Note that the module depends on [Networkx](https://networkx.github.io/), which is shipped with SageMath. Therefore, it should work using Sage as well as with any Python installation, provided the Networkx library is available.

### CODE REVIEW

**Comment by enadeau** [comment]
I change the code to make it dependant on Sage graph.
 
I think it could be interesting to include this case in ``ComputeL`` with an option.
 For example``ComputeL(T, optimization='tree')`` can use the dynamic programming algorithm with a warning that no example will be provide.
We can even take ``optimization in [None, 'tree', 'cube']`` to call the cube optimization from the main function.

**Comment by ablondin** [comment]
Hi!

Thanks for the quick feedback. I agree with your changes to make it dependent on Sage for consistency purposes.

Also, I completely agree with your idea to merge the different solutions and choose the right algorithm according to whether the graph is general, a tree, or an hypercube graph, but this could probably decided automatically (at least, it is easy to check if the graph is a tree, and then to trigger the dynamic program, I'm not sure if we can easily decide if a given graph is an hypercube graph?).

**Comment by ablondin** [comment]
I'll try to work on it tomorrow.

**Comment by ablondin** [comment]
I just rebased the branch on `develop` since #4 has been merged.

**Comment by enadeau** [comment]
Centralization needs to be complete by implementing the function ``leaf_map_with_example``` in ``LeafMapDynamicProgram``. Also the readme needs to be update.

**Comment by enadeau** [comment]
Centralization needs to be complete by implementing the function ``leaf_map_with_example``` in ``LeafMapDynamicProgram``. Also the readme needs to be update.

**Comment by ablondin** [comment]
I just rebased this branch on `develop`, to take into account #8 and #9.

I had only one conflict in commit 2434872. All tests still pass, but if you could take a quick look to make sure that I didn't make any mistake, that would be appreciated.

I'm working now on providing examples in the tree case. It shouldn't be too hard...

**Comment by ablondin** [comment]
Arrrrrgh! It's harder than I thought, I have to generalize some of the functions. I'll try to finish this during the week-end.

**Comment by ablondin** [comment]
Hi, Émile!

I'm busier than I expected this week so I was wondering if you would feel comfortable trying to complete this pull request. If you're too busy yourself, then forget it, but if you think it would be a good exercise :), then feel free to work on this part.

Just let me know what you decide, so that I don't work unnecessarily in case I find some free time in the next days.

Thanks!

**Comment by ablondin** [comment]
@enadeau : All right! I think I finally managed to correctly produce examples of fully leafed induced subtrees in the tree case!

It's probably better that your double check everything, since I had to change many pieces of code. In particular, the function `Lf` is now cached when computing the leaf function. I don't know if we should mention it in the DMTCS paper, though, but it changes the space complexity, which is now `O(n^2\delta)`...

Note that I rebased the whole branch to get rid of duplicate commits that you added when merging the branch. The best way to do this is the following, assuming that my repo's remote name is `ablondin` and your local branch is `tree-case`:
```sh
git fetch ablondin # To retrieve my branch
git checkout ablondin/tree-case # To change the state to my branch
git checkout -B tree-case
```
Then, you can work on the branch to make sure everything is OK.

Let me know if everything works.

**Comment by enadeau** [comment]
Every thing looks good to me. I made many test and the examples are always good.

**Comment by ablondin** [comment]
Just a last remark. I said above that the spatial complexity had changed because of the now cached function `Lf`, but I realized that I was wrong (well, I think I was wrong). We'll have to discuss it in person just to make sure my reasoning is OK, but this does not have any impact on the current pull request.

Therefore, fell free to merge it whenever you're ready.

**Pull request merged**
