### PR TITLE
Add examples to REAME file with images

### PR DESCRIPTION
**Pull request by ablondin**
This pull request intends to add some examples with images in the README file. This way, readers will understand better the usefulness of the project.

Depends on #10.

### CODE REVIEW

**Comment by enadeau** [comment]
@ablondin 
I think  it will be nice to have green edges for the subtrees. I can work on it if you agree.

Also, I think this branch needs a rebase to get rid of all the commits that were parts of PR #10 .

**Comment by ablondin** [comment]
I'll try to rebase now!

**Comment by ablondin** [comment]
I see. When your merged, you squashed the commit, so I had to rebase everything. There are only two additional commits to check now.

**Comment by enadeau** [comment]
I think it's now good. If you agree I will squash and merge.

**Comment by ablondin** [comment]
Looks good to me! But I think it's better not to squash, each commit is quite descriptive. Thanks for the green edges!

**Pull request merged**
