### PR TITLE
Check if a graph is an hypercube

### PR DESCRIPTION
**Pull request by ablondin**
In the function `ComputeL` (which is renamed `leaf_map` in #10), when the user choose `algorithm=cube`, there is an assertion that checks if the given graph has the right number of vertices.

Clearly, this is not sufficient to guarantee that the graph is indeed an hypercube. This pull request intends to fix this problem by providing a function that does a complete verification. The solution is inspired from one of the answers found at https://www.quora.com/Given-the-vertices-and-edges-of-a-graph-how-does-one-verify-that-the-graph-is-a-hypercube-graph. Depends on #10.

### CODE REVIEW

**Comment by ablondin** [comment]
Also rebased this branch.

**Comment by ablondin** [comment]
There is a difference between `:` and `::`. When there are two `::`, this is because it is followed by a sage code block, while a single `:` is followed by a text paragraph (there is no indentation).

As for the singular/plural, I don't mind if it varies according to whether there is one or more examples, but you can make it more uniform if you want, I'm also OK with that.

**Comment by enadeau** [comment]
Can you rebase this branch on top of develop?

**Comment by ablondin** [comment]
Done.

**Comment by enadeau** [comment]
@ablondin If you agree with my changes, I think it's ready to merge.

**Comment by ablondin** [comment]
I'm OK for the merge.

**Pull request merged**
