### PR TITLE
Removes the use of Infinity constant

### PR DESCRIPTION
**Pull request by enadeau**
I've removed the use of sage's Infinity which was in fact really time consuming. You can see the differences in timing on the picture. It is quite relevant.
capture du 2018-02-27 16-10-02
 For two graphs, you have first the timing with the code on the branch and then the timing with code on develop.

### CODE REVIEW

**Review by ablondin — CHANGES_REQUESTED** [review]
Nice! Just a minor modification: It is best practice in Python to write `is None` instead of `== None`. See http://jaredgrubb.blogspot.ca/2009/04/python-is-none-vs-none.html for a discussion about it.

**Comment by enadeau** [comment]
I make the changes and find more of these ``== None`` in older code. I've also change them.

**Comment by ablondin** [comment]
+1

**Review by ablondin — APPROVED** [review]

**Comment by ablondin** [comment]
Feel free to merge whenever you're ready!

**Pull request merged**
