### PR TITLE
Clean the file

### PR DESCRIPTION
**Pull request by enadeau**
I start to clean the main file

### CODE REVIEW

**Comment by ablondin** [comment]
Since `LeafFunction` is a function, you should use `leaf_function`.

**Comment by ablondin** [comment]
Also, it is not recommended to put spaces around the `=` sign when passing arguments.

For instance
```python
ComputeL(graphs.CubeGraph(3), algorithm = 'cube')
```
should be
```python
ComputeL(graphs.CubeGraph(3), algorithm='cube')
```

**Comment by ablondin** [comment]
I also cleaned a bit the files. Below are the main modifications:

- I renamed the file `graph_border.py` to `configuration.py`;
- I renamed the file `induced_maximal_tree.py` to `flis_graphs.py`;
- I changed the README file to ReStructuredFormat so that we can test it automatically with Sage;
- The rest is mostly rephrasing of documentation and syntax fixes.

**Comment by ablondin** [comment]
@enadeau: Ok, I think I'm done with this part. You can merge if you agree with my changes.

**Comment by enadeau** [comment]
I correct a last typo. I will merge.

**Pull request merged**
