### PR TITLE
Provide complete example

### PR DESCRIPTION
**Pull request by enadeau**
Summary of changes:

- Return example of fully leafed tree for the general cases
- Return example for cube graph when the leaf function is realized with a i-pode

Still need to be done: Add examples when a fully leafed tree in Q_d is a snake.

### CODE REVIEW

**Comment by ablondin** [comment]
Good!

What about manually insert the snake examples? According to our computation for the cases *d = 2,3,4,5,6*, where *d* is the dimension of the hypercube, the only cases where the solution is a snake is if *i = 2,3* or if *(i,d) = (5,3)*.

Now, since we have not proved that these are the only cases, you could safely add an assertion stating that there are not other cases, so that the assertion would be triggered and would warn the user in the case where other snakes have been missed.

Does it seem reasonable?

**Comment by ablondin** [comment]
Nice! This seems good.

One last request, though. It might look like a detail, but it might be useful later. Consider the following code:
~~~python
sage: load('induced_maximal_tree.py')
sage: (L,E) = CubeGraphLeafFunction(3)
sage: L
{0: 0, 1: 0, 2: 2, 3: 2, 4: 3, 5: 2, 6: 0, 7: 0, 8: 0}
sage: E
{0: [],
 1: [['000']],
 2: [['000', '100']],
 3: [['000', '100', '010']],
 4: [['000', '100', '010', '001']],
 5: [],
 6: [],
 7: [],
~~~

I think we should have `0: [[]]` instead of `0: []` to distinguish between the case where there is one solution (the empty tree is really a tree and has 0 leaves) in comparison when there is none (the cases 5, 6, 7).

**Comment by ablondin** [comment]
Also, the value `8` is missing from the domain (the keys of `L` should be the same as the keys in `E`).

**Comment by enadeau** [comment]
I fix the problem for ``0`` but cannot reproduce your example for the problem with the domain of ``E``.

I was wondering if we should change the value of ``L[i]`` to ``None`` where there's no induced subtree of this size.

**Comment by ablondin** [comment]
I just noticed that I didn't paste my example correctly (there is no closing brace). So forget about the comment on the domain of `E`, I was wrong.

I agree with your idea of setting `L[i] = None` when there is no induced subtree.

And this makes me think that you should also change `E`... More precisely, `E[i]` should return *one* list of vertices forming an induced subtree instead of a list containing another list. Therefore, the result should be the following:
~~~python
sage: load('induced_maximal_tree.py')
sage: (L,E) = CubeGraphLeafFunction(3)
sage: L
{0: 0, 1: 0, 2: 2, 3: 2, 4: 3, 5: 2, 6: None, 7: None, 8: None}
sage: E
{0: [],
 1: ['000'],
 2: ['000', '100'],
 3: ['000', '100', '010'],
 4: ['000', '100', '010', '001'],
 5: None,
 6: None,
 7: None,
 8: None}
~~~

**Comment by enadeau** [comment]
The reason for list of list is that the program can return multiple examples of fully leafed tree for the same size. I think it can be interesting to have many example so we should keep the code this way. For example:

~~~python
sage: CubeGraphLeafFunction(4)[1][8]

[['0000', '1000', '0100', '0010', '1001', '0011', '0111', '1111'],
['0000', '1000', '0100', '0010', '1001', '0011', '0111', '1101'],
['0000', '1000', '0100', '0010', '1001', '1101', '1111', '0111']]
~~~

**Comment by ablondin** [comment]
All right! Just checked it and everything seems fine. You can merge the pull request whenever you're ready! Good work!

**Pull request merged**
